### ISSUE TITLE
720p

### ISSUE THREAD

**Issue by Elite** [maple3142/ytdl#1]
Not showing 720p links anymore!!

**Comment by maple3142** [comment]
Example?

**Comment by Elite** [comment]
https://maple-ytdl.herokuapp.com/?id=T2pdmZhDXfo&format=1

The example video has 720p but no link in json.

**Comment by maple3142** [comment]
![image](https://user-images.githubusercontent.com/9370547/45548451-f7451c80-b856-11e8-8f39-ae0335ae467d.png)
This video doesn't have 720p.

**Comment by Elite** [comment]
My bad there are two demo url's in your example :(
