### ISSUE TITLE
hi,最近在使用ytdl解析video获取视频地址时出现Invalid regular expression，不知道是否属于正常情况

### ISSUE THREAD

**Issue by chinecc** [maple3142/ytdl#10]
以下错误代码提示是在终端会收到，但是程序执行是有返回相关的结果，能够获取到相关video的info，
不知道有没有办法屏蔽这个错误提示或者修复的办法？

> use fallback SyntaxError: Invalid regular expression: /c)));d&&g.R=function\((.+?)\){(.+?)}/: Unmatched ')'
>     at new RegExp (<anonymous>)
>     at parsedecsig (/Users/xxxx/ytdl/decsig.js:39:31)
>

**Comment by maple3142** [comment]
更新一下 ytdl 程式本身就好了
因為之前在改腳本版的 regex 的時候忘記回來改這邊的 regex

**Comment by chinecc** [comment]
非常感谢。 Its works now.
