### ISSUE TITLE
部分影片無法正常取得

### ISSUE THREAD

**Issue by LinZap** [maple3142/ytdl#12]
非常感謝您的教學範例，但我使用的過程中有**部分**影片無法正常取得資源，我把錯誤回報給您

## 案例1

程式擲出錯誤

* Youtube 影片連結：https://www.youtube.com/watch?v=3ueoUu5_pUs
* Youtube 影片 Info 連結：https://www.youtube.com/get_video_info?eurl=http%3A%2F%2Fkej.tw%2F&sts=18372&video_id=3ueoUu5_pUs
* 程式錯誤訊息：
```
use fallback ReferenceError [Error]: yt is not defined
    at playerBootstrap (vm.js:1:66960)
    at vm.js:1:67207
    at Script.runInContext (vm.js:137:20)
    at D:\Node\ytdl\node_modules\vm2\lib\main.js:778:53
    at timeout_bridge.js:1:1
    at Script.runInContext (vm.js:137:20)
    at doWithTimeout (D:\Node\ytdl\node_modules\vm2\lib\main.js:462:17)
    at VM.run (D:\Node\ytdl\node_modules\vm2\lib\main.js:776:10)
    at exports.runInContext (D:\Node\ytdl\sandboxutil.js:5:12)
    at D:\Node\ytdl\decsig.js:62:4
```

## 案例2

有正常取得資源連結，但無法正常取得音訊資源

* Youtube 影片連結：https://www.youtube.com/watch?v=3YEOoZJMyvU
* Youtube 影片 Info 連結：https://www.youtube.com/get_video_info?eurl=http%3A%2F%2Fkej.tw%2F&sts=18372&video_id=3YEOoZJMyvU
* 取得資源時報錯
```
存取 r2---sn-u4h-un5l.googlevideo.com 的要求遭到拒絕您未獲得授權，無法瀏覽這個網頁。
HTTP ERROR 403
```
* 取得的音訊 URL：https://r2---sn-u4h-un5l.googlevideo.com/videoplayback?expire=1587830784&ei=oAukXteHGY_NgQOzkaywBQ&ip=49.159.128.216&id=o-ALR2xyBDZA-2wthHwQ7q0seMfvXVhyccocORa1RXJ1rs&itag=140&source=youtube&requiressl=yes&mh=No&mm=31%2C29&mn=sn-u4h-un5l%2Csn-un57en7l&ms=au%2Crdu&mv=m&mvi=1&pl=21&gcr=tw&initcwndbps=1241250&vprv=1&mime=audio%2Fmp4&gir=yes&clen=4529786&dur=279.846&lmt=1585837262858746&mt=1587809089&fvip=3&keepalive=yes&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRgIhAKfG_nLhFcdEj4jsoTBxAsnK_z2bE5BMjnSeswZbzOiPAiEAnM2u6f20x-lD_qbIf9jBFxUJwQbehgI2RVppN5SGrYc%3D&sig=rJpiJpPlLswRgIhAsiW8V3Sdz8HD-TiNNfQLPv0Ax8RNk25xb6JKX4wFJwgAiEA7MnPNua3_h5bL7fr-96w4=gPm3poLuHm46YYshKXanE=nEo

**Comment by maple3142** [comment]
我也不曉得
