### ISSUE TITLE
error 'The page isn't redirecting properly'

### ISSUE THREAD

**Issue by ccdd13** [maple3142/ytdl#14]
**tested links**:
  - https://ytdl.maple3142.net/api?id=-tKVN2mAKRI
  - https://ytdl.maple3142.net/api?id=hNQB5Qx6zaM
  - https://ytdl.maple3142.net/api
  - https://ytdl.maple3142.net

**HAR logs**:
https://gist.github.com/ccdd13/c2372ceab38711370b450976eca4cdf8

**browser** : firefox 76.0.1 (64-bit)

**error message**
```js
The page isn't redirecting properly

An error occurred during a connection to ytdl.maple3142.net.

    This problem can sometimes be caused by disabling or refusing to accept cookies.

```

**Comment by maple3142** [comment]
It works now
