### ISSUE TITLE
The YouTube get_video_info API seems to be dead

### ISSUE THREAD

**Issue by Prcuvu** [maple3142/ytdl#16]
The API `https://www.youtube.com/get_video_info?video_id=${id}&el=detailpage` returns HTTP 404.
Therefore your JSON API `https://ytdl.maple3142.net/api?id=${id}` always returns "Adblock conflict".

**Comment by Prcuvu** [comment]
The video info JSON is now embedded inside the `watch?v=${id}` response.
Inside a `<script>` block there is `var ytInitialPlayerResponse = {video info JSON};`. The formats are recorded inside its `.streamingData.formats`.

**Comment by thisistorsten** [comment]
Yes it is. Here is an example to resolve the problem. 
https://github.com/snakx/YouTubeApiSharp/commit/e0432b36f7416974548d56f33e27a48576b36e98
