### ISSUE TITLE
hi,又要来麻烦你帮忙确认一个问题？我把代码clone布署到我的服务器上返回生成的url还是出现了403，但我在本地localhost时是能正常使用，不知道是哪里还需要做配置？

### ISSUE THREAD

**Issue by chinecc** [maple3142/ytdl#5]
普通的video没有问题，
主要还是带signature的影片，
因为我还没买https证书，
在服务器这边只是简单的开启了ip地址访问api，
不知道是不是必须要绑定域名加https才可以？

另外我尝试使用readme里面提供的的接口地址，加上我要下载的videoId，
比如 https://maple3142-ytdl.glitch.me/api?id=jUeryEph6uc  

返回过来的url也是同样403错误，
只有在本地localhost访问返回过来的url可以正常的能下载。
如果可以的话，希望您能帮忙在做一下协助

**Comment by maple3142** [comment]
我看不了這影片，所以可能這個本來就有問題 https://www.youtube.com/watch?v=jUeryEph6uc
而其他我能看的影片(如: https://www.youtube.com/watch?v=TXzfQ0cP1P0)，即使有 signature 也能正常取得: https://maple3142-ytdl.glitch.me/api?id=TXzfQ0cP1P0

Edited:
後來發現這是地區限制的問題，你這個影片是有限定特定區域瀏覽的，例如我用香港 proxy 就能通過了

**Comment by chinecc** [comment]
哦。 那我弄一台香港的服务器试一下。多谢你了 :)
