### ISSUE TITLE
hi,有关个别影片的url在locahost解析能正常下载播放，放在server上面无法工作的问题，我发现找到原因了，不知道你这边能否帮忙确认一下？

### ISSUE THREAD

**Issue by chinecc** [maple3142/ytdl#6]
我是在这个地方了解到  https://github.com/fent/node-ytdl-core/issues/434#issuecomment-503307225  
这个老外也有同样的问题，
youtube这边针对一些 video，它是限制了只有当前访问ip 才能访问，
比如我们解析出来这样的url:

https://r3---sn-4g5e6nez.googlevideo.com/videoplayback?expire=1561305511&ei=R00PXY78K9WKVs7ntbAJ&ip=82.234.194.1&id=o-ANEPRjYC1uJ3bX4QcSUV6CJuVGXzdHxqSP-Rb5C6W5TV&itag=22&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-4g5e6nez%2Csn-4gxx-25gee&ms=au%2Crdu&mv=m&pl=15&nh=%2CEAE&gcr=fr&initcwndbps=637500&mime=video%2Fmp4&ratebypass=yes&dur=4008.901&lmt=1560702935607179&mt=1561283809&fvip=7&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cmime%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl%2Cnh%2Cinitcwndbps&lsig=AHylml4wRQIgdPTIG6t5iT0lpD8z7PmpI26Aux--9MwTHQztVZ-w3rECIQDDJwVJKFZ61XCavQXmyA1nsh--vpNBaIrc3AFJeH4ZHw%3D%3D&sig=ALgxI2wwRQIgZxbWhzD_JImSbV5FsgavJWOHx1DpamZJZi30suowLbICIQDy7E-50PMbCWgxmeblMJBkPR28I6Vb8HhK0gKIw3OIPw==

这其中的ip=82.234.194.1 是我本地的ip，所以在本地点击过去是能正常播放和下载的，
如果是在server上面解析出来，ip这边会是服务器的ip，然后我在电脑这边访问服务器这边解析出来的url，就会出现403，因为ip不同导致。

所以我的问题是，有没有办法让解析程序这边把 ip这一参数单独处理，替换为 当前访问的ip值上去，让youtube认为是当前浏览器这边的访问ip在访问然后去生成url，我想这样就能解决个别video出现403问题了。 

希望大神在帮忙看看这个方案有没有可行性？

**Comment by maple3142** [comment]
我直接測試了改 ip 參數的方法，完全沒有效果
我也測試了其他原理類似的網站，也有一樣的問題: https://www.youtubeto.com/zh/ (此網站的"下載mp4")

**Comment by chinecc** [comment]
哦。那看来是没办法了。不过还是很感谢的回复。 :)
