### ISSUE TITLE
JSON api 失败

### ISSUE THREAD

**Issue by zhangyu7403** [maple3142/ytdl#7]
https://maple3142-ytdl.glitch.me/api?id=T2pdmZhDXfo&format=1     没有返回需要的数据

**Comment by maple3142** [comment]
因為我拿來作demo的網站有人拿來做一些奇怪的事，例如log中看到最多的是這個IP: 149.129.118.81
這是因為大量對youtube的request導致glitch.com的伺服器被YouTube方封鎖了(HTTP 429)

等我限制一下每個ip可發送的request數量就好了

**Comment by maple3142** [comment]
ok 已修復完成
