### ISSUE TITLE
How to convert PHP based 

### ISSUE THREAD

**Issue by imlucky01** [maple3142/ytdl#9]
Your script is java Based. How to change PHP based Script.
Thank You.

**Comment by maple3142** [comment]
Rewrite all of them in php?
Besides, this is JavaScript not Java.

**Comment by imlucky01** [comment]
Yes Sir. I can't understand Other languages.

**Comment by maple3142** [comment]
I am not familiar with PHP, so you could find someone understand both JS and PHP to rewrite this.
